name: Deploy race server

on: workflow_dispatch

jobs:
  deploy:
    runs-on: [self-hosted, boltcrate]
    steps:
      - name: Download latest release
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: 'Lawrence-linux-x64.zip'
          extract: true

      - name: Stop service
        run: sudo systemctl stop lawrence-race

      - name: Overwrite old data
        run: ls -l * && cp -R * /opt/LawrenceRace/

      - name: Start service
        run: sudo systemctl start lawrence-race